### ISSUE TITLE
beans.xml header in Java EE 8 should reference CDI 2.0 instead of 1.1

### ISSUE THREAD

**Issue by gmanjon** [AdamBien/javaee8-essentials-archetype#1]
https://github.com/AdamBien/javaee8-essentials-archetype/blob/11a166f55580c8e19a8e783115915dcad8828762/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/beans.xml#L4

**Comment by AdamBien** [comment]
Thanks! Fixed in 0.0.4
